function randomizeFromArray(array) {
  return array[Math.floor(Math.random() * array.length)];
}

////////////////////////////////////////////////////////////////////////////////////copied instead of exporting
function pickFromList(pickedList) {
  if (pickedList.type === "mixerSpaced") {
    const nonTypeKeys = Object.keys(pickedList).filter((key) => {
      return key !== "type";
    });
    let combinedParts = "";
    for (let k = 0; k < nonTypeKeys.length; k++) {
      combinedParts += ` ${randomizeFromArray(pickedList[nonTypeKeys[k]])}`;
    }
    return combinedParts;
  } else if (pickedList.type === "mixerConcatenated") {
    const nonTypeKeys = Object.keys(pickedList).filter((key) => {
      return key !== "type";
    });
    let combinedParts = "";
    for (let k = 0; k < nonTypeKeys.length; k++) {
      combinedParts += randomizeFromArray(pickedList[nonTypeKeys[k]]);
    }
    return combinedParts;
  } else if (pickedList.type === "picker") {
    return randomizeFromArray(pickedList.list);
  } else if (pickedList().type === "pickerRoller") {
    // pickerRollers (e.g. random encounters, corpse loot) are functions, so that the numbers are rerolled each time
    return randomizeFromArray(pickedList().list);
  }
}
////////////////////////////////////////////////////////////////////////////////////copied instead of exporting




export const orkishNames = {
  type: "mixerConcatenated",
  prefix: [
    "Kronn", "Khaz", "Tro", "Bora", "Urg", "Zora", "Scal", "Krell", "Vora", "Mor",
    "Dra", "Sor", "Var", "Ul", "Ja", "Kresh", "Za", "Tor", "Rok", "Gar", "Isk", 
    "Zira", "Va", "Gralk", "Ran", "Korv", "Hro", "Tra", "Brol", "Arr", "Bad", 
    "Giga", "Zag", "Bog", "Bol", "Bor", "Ba", "Brak", "Brog", "Brug", "Bull", 
    "Buzz", "Dakka", "Deff", "Drag", "Dreg", "Duz", "El", "Garag", "Garga", "Gaz", 
    "Gha", "Ghar", "Ghaz", "Ghur", "Gitz", "Glut", "Go", "Gol", "Gor", "Mag", 
    "Grag", "Grash", "Grim", "Gri", "Grob", "Grokk", "Grom", "Grosh", "Groz", 
    "Grug", "Gruk", "Grung", "Grukk", "Gul", "Gut", "Hag", "Hruk", "Jud", "Khor", 
    "Koz", "Krak", "Kraz", "Krugg", "Kug", "Kur", "Mar", "Ma", "Mog", "Mug", 
    "Mur", "Naz", "Urd", "Nog", "Noz", "Nur", "Nurk", "Nuzz", "Ogr", "Orka", 
    "Rar", "Raz", "Rip", "Shagg", "Shank", "Shokk", "Skag", "Skar", "Skrog", 
    "Snagga", "Snag", "Thog", "Trag", "Ug", "Ugul", "Ung", "Ur", "Uz", "Vor", 
    "Vorh", "Wug", "Zan", "Zhad", "Zog", "Zorg", "Az", "Dur", "Og", "Tau", 
    "Urk", "Vag", "Wyrr", "Rug", "Balc", "Bolg", "Golfim", "Grish", "Lag", 
    "Lug", "Mau", "Muz", "Orco", "Oth", "Rad", "Shag", "Snaga", "Uft", "Nazg", 
    "Ash", "Durba", "Gim", "Thraka", "Bur", "Burz", "Krim", "Durb", "Carnish", 
    "Gazat", "Ghash", "Glob", "Krimp", "Nugu", "Ombi", "Ronk"
  ],
  suffix: [
    "ghul", "ga", "al", "ana", "ak", "gar", "la", "na", "vash", "ara",
    "tak", "ra", "sha", "gan", "go", "an", "gard", "dakka", "fang", "frag",
    "gob", "lob", "grog", "krull", "ok", "rag", "ka", "rok", "gark", "bad",
    "natz", "grakka", "goz", "hak", "koz", "mek", "shul", "zulk", "grim",
    "kul", "ghkull", "rk", "mott", "tok", "bag", "baz", "drang", "grok", "gutz",
    "kug", "lad", "rath", "shag", "snik", "ash", "zod", "bakh", "shak",
    "skull", "snag", "tusk", "shnak", "znak", "smak", "nok", "pit", "bok",
    "drak", "dungus", " Dungus", "grudd", "spar", "rog", "grob", "nag", "rutz", "guz",
    " Krosnik", "za", "drug", "shogg", "goulth", "lurk", "gor", "dreg", "grub",
    "rub", "grot", "gok", "grond", "uk", "mungus", "guts", "gukk", "grod",
    "ro", "grin", "rod", "skraga", "hard", "skar", "gak", "guk", "lakk",
    "zog", "gall", "gnott", "had", "zark", "bog", "zag", "snark", "ax",
    "rond", "og", "hag", "gut", "kol", "or", "glum", "lok", "grek", "raz",
    "lud", "meg", "dog", "bul", "gol", "nakh", "duf", "dush", "hur", "gash",
    "bal", "bug", "rat", "luk", "nazg", "tuluk", "batul", "zum", "burz",
    "ishi", "patul", "durb", "glob", "gul", "ronk", "zagh",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ]
}

export const maleSlavicNames = {
  type: "picker",
  list: [
    "Bachorza",
    "Baran",
    "Barcław",
    "Barcsław",
    "Barnim",
    "Barnisław",
    "Bądzsław",
    "Bąsław",
    "Bdzigost",
    "Bedgost",
    "Bezprym",
    "Będomir",
    "Będzieciech",
    "Będziemir",
    "Będziemirz",
    "Będzimir",
    "Będzimysł",
    "Biecław",
    "Biecsław",
    "Biestryj",
    "Biezdar",
    "Biezdziad",
    "Biezpraw",
    "Biezprzem",
    "Biezprzym",
    "Biezrząd",
    "Biezstryj",
    "Biezstryk",
    "Biezuj",
    "Biezwuj",
    "Blizan",
    "Blizbor",
    "Blizborz",
    "Bochwał",
    "Bodan",
    "Bodzepor",
    "Bofał",
    "Bogchwał",
    "Bogdaj",
    "Bogdał",
    "Bogdan",
    "Bogdasz",
    "Bogfał",
    "Bogmieł",
    "Bogmił",
    "Bogodał",
    "Bogodan",
    "Bogodar",
    "Bogofał",
    "Bogomieł",
    "Bogomił",
    "Bogosław",
    "Bogowid",
    "Bogsław",
    "Boguchał",
    "Boguchwał",
    "Bogudan",
    "Bogudar",
    "Bogufał",
    "Bogumieł",
    "Bogumił",
    "Bogumysław",
    "Bogurad",
    "Bogured",
    "Bogusąd",
    "Bogusław",
    "Bogwidza",
    "Bogwiedz",
    "Bohusław",
    "Bojan",
    "Bolan",
    "Bolebor",
    "Boleczaj",
    "Boleczest",
    "Bolegor",
    "Bolelut",
    "Bolemir",
    "Bolemysł",
    "Bolesław",
    "Bolesta",
    "Bolęta",
    "Bolibąd",
    "Bolibor",
    "Bolko",
    "Boromir",
    "Borut",
    "Boruta",
    "Borzej",
    "Borzęta",
    "Borzgniew",
    "Borzuj",
    "Borzygniew",
    "Borzym",
    "Borzymir",
    "Borzysław",
    "Borzywoj",
    "Borzywuj",
    "Bosław",
    "Bożciech",
    "Bożdar",
    "Bożebor",
    "Bożeciech",
    "Bożydar",
    "Bożysław",
    "Bracsław",
    "Branibor",
    "Bratek",
    "Bratmił",
    "Bratomił",
    "Bratomir",
    "Bratosław",
    "Bratosz",
    "Bratumił",
    "Braturad",
    "Bratysław",
    "Bretmił",
    "Bretomił",
    "Brocsław",
    "Broda",
    "Brodzisław",
    "Bromir",
    "Bronimir",
    "Bronisąd",
    "Bronisław",
    "Broniwoj",
    "Bronsław",
    "Brosław",
    "Brunisław",
    "Brzestryk",
    "Brzezdob",
    "Brzezdoma",
    "Brzezpraw",
    "Brzezstryk",
    "Budziboj",
    "Budzigniew",
    "Budzimir",
    "Budzisław",
    "Budziwoj",
    "Budziwuj",
    "Budzsław",
    "Budźwoj",
    "Byczek",
    "Bygost",
    "Bytomir",
    "Chalimir",
    "Chalisław",
    "Chełst",
    "Chocian",
    "Chociebąd",
    "Chociebor",
    "Chociemir",
    "Chociesław",
    "Chocimier",
    "Chocimir",
    "Chocimirz",
    "Chocsław",
    "Choroman",
    "Chotobor",
    "Chrap",
    "Chudz",
    "Chwalęta",
    "Chwalibog",
    "Chwalimir",
    "Chwalisław",
    "Cibor",
    "Cich",
    "Ciechomir",
    "Ciechosław",
    "Ciecierad",
    "Cieciered",
    "Ciecimiar",
    "Ciecirad",
    "Cieciurad",
    "Ciećrad",
    "Cierpisław",
    "Ciesław",
    "Cieszbor",
    "Cieszęta",
    "Cieszmiar",
    "Cieszmier",
    "Cieszmir",
    "Cieszybor",
    "Cieszygor",
    "Cieszym",
    "Cieszymiar",
    "Cieszymier",
    "Cieszymir",
    "Cieszymysł",
    "Cieszyrad",
    "Cieszysław",
    "Cirzpibog",
    "Cirzpisz",
    "Cis",
    "Cisław",
    "Czabor",
    "Czajęta",
    "Czasław",
    "Czcibor",
    "Czcirad",
    "Czcisław",
    "Czedrog",
    "Czesbor",
    "Czesław",
    "Czębor",
    "Czędomir",
    "Częsbor",
    "Częstobor",
    "Częstogoj",
    "Częstomir",
    "Częstowoj",
    "Czścibor",
    "Dadzbog",
    "Dalbor",
    "Dalebor",
    "Daleborz",
    "Dalegor",
    "Dalemiar",
    "Dalemir",
    "Dalestryj",
    "Dalewin",
    "Dalibor",
    "Dalimiar",
    "Dalimir",
    "Dalwin",
    "Dargomier",
    "Dargorad",
    "Dargosław",
    "Derwan",
    "Długomił",
    "Dobiegniew",
    "Dobielut",
    "Dobiemiar",
    "Dobiemier",
    "Dobiemiest",
    "Dobiemir",
    "Dobiesław",
    "Dobimir",
    "Dobosław",
    "Dobrobąd",
    "Dobrociech",
    "Dobrogniew",
    "Dobrogost",
    "Dobrogoszcz",
    "Dobromier",
    "Dobromił",
    "Dobromir",
    "Dobromysł",
    "Dobromysław",
    "Dobrosiodł",
    "Dobrosław",
    "Dobrosuł",
    "Dobrowit",
    "Dobrowoj",
    "Dobrutro",
    "Dobrzegniew",
    "Domabor",
    "Domaborz",
    "Domagniew",
    "Domamir",
    "Domarad",
    "Domaradz",
    "Domared",
    "Domasław",
    "Domastoj",
    "Domastryj",
    "Domasuł",
    "Domauj",
    "Domawuj",
    "Domażyr",
    "Domiemir",
    "Domk",
    "Domorad",
    "Domosław",
    "Drahobysz",
    "Drahomir",
    "Drogmir",
    "Drogodziej",
    "Drogomił",
    "Drogomir",
    "Drogomysł",
    "Drogoradz",
    "Drogosław",
    "Drogowit",
    "Drohobysz",
    "Drohomir",
    "Dromił",
    "Dziebor",
    "Dziersław",
    "Dzierżykraj",
    "Dzierżysław",
    "Dziesław",
    "Dzik",
    "Dzirsław",
    "Dzirżykraj",
    "Dzirżysław",
    "Dzirżyterg",
    "Dzirżywuj",
    "Dzisław",
    "Dziwigor",
    "Dziwisław",
    "Falibog",
    "Falibor",
    "Falimir",
    "Falimirz",
    "Falisław",
    "Gardomir",
    "Gęba",
    "Głowka",
    "Gniemir",
    "Gnierat",
    "Gniewko",
    "Gniewomiar",
    "Gniewomier",
    "Gniewomir",
    "Gniewosz",
    "Gocław",
    "Godosław",
    "Godzimir",
    "Godzisław",
    "Godzsław",
    "Gogoła",
    "Gołek",
    "Goły",
    "Gorazd",
    "Gorsław",
    "Gorzysław",
    "Gosław",
    "Gostmił",
    "Gostomysł",
    "Gościmiar",
    "Gościmir",
    "Gościrad",
    "Gościsław",
    "Gościwid",
    "Gościwit",
    "Gościwuj",
    "Goworek",
    "Grochot",
    "Grodzisław",
    "Grodzsław",
    "Gromisław",
    "Grot",
    "Grzmisław",
    "Grzymisław",
    "Grzymosław",
    "Grzymsław",
    "Grzysław",
    "Himisław",
    "Hodysław",
    "Hubysław",
    "Huniemir",
    "Huniesław",
    "Imisław",
    "Izasław",
    "Izbelut",
    "Izbor",
    "Izbygniew",
    "Izbylut",
    "Jaczemir",
    "Jaczewoj",
    "Jaksa",
    "Janisław",
    "Jarogniew",
    "Jaromiar",
    "Jaromir",
    "Jaropełk",
    "Jarosław",
    "Jarostryj",
    "Jawor",
    "Jerogniew",
    "Jeromiar",
    "Jeromier",
    "Jerosław",
    "Jezior",
    "Jeż",
    "Jimisław",
    "Jirosław",
    "Juniesław",
    "Jutrogost",
    "Jutrowoj",
    "Jutrowuj",
    "Kajmir",
    "Kalmir",
    "Kanimier",
    "Kanimir",
    "Kanmił",
    "Karna",
    "Kazimiar",
    "Kazimier",
    "Kazimierz",
    "Kazimir",
    "Kazimirz",
    "Kaźmir",
    "Kąkol",
    "Kierz",
    "Kłobuczek",
    "Kobyłka",
    "Kochan",
    "Kociebor",
    "Kociemiar",
    "Kociemier",
    "Kociemir",
    "Kocimiar",
    "Kocimier",
    "Kocimir",
    "Koćmir",
    "Komor",
    "Koprzywa",
    "Korostawic",
    "Korostawiec",
    "Kościoł",
    "Kożuszek",
    "Krasa",
    "Krost",
    "Krupa",
    "Kruszk",
    "Krzecsław",
    "Krzesąd",
    "Krzesimir",
    "Krzesisław",
    "Krzesław",
    "Krzysław",
    "Krzywosąd",
    "Krzyż",
    "Kupimir",
    "Kusza",
    "Kwalimir",
    "Kwalisław",
    "Kwiatek",
    "Laliczaj",
    "Lasota",
    "Lech",
    "Lechosław",
    "Lederg",
    "Lelistryj",
    "Lesław",
    "Leszek",
    "Lis",
    "Litobor",
    "Luba",
    "Lubgost",
    "Lubodrog",
    "Lubomir",
    "Lubomirz",
    "Lubomysł",
    "Luboradz",
    "Lubowid",
    "Lucsław",
    "Ludmar",
    "Ludmił",
    "Ludomer",
    "Ludomił",
    "Ludomir",
    "Ludosław",
    "Ludziwoj",
    "Lutmiar",
    "Lutobor",
    "Lutogniew",
    "Lutomiar",
    "Lutomir",
    "Lutomysł",
    "Lutosław",
    "Lutsław",
    "Łękomir",
    "Łopata",
    "Małobąd",
    "Małogost",
    "Małomir",
    "Małostryj",
    "Małostryk",
    "Małowid",
    "Małowuj",
    "Manomir",
    "Markusław",
    "Masław",
    "Matuł",
    "Mezamir",
    "Męcimir",
    "Męcisław",
    "Męcsław",
    "Męsław",
    "Miecisław",
    "Miecsław",
    "Mieczysław",
    "Miełosław",
    "Miesław",
    "Miestwin",
    "Mieszek",
    "Mieszko",
    "Milan",
    "Milej",
    "Milęta",
    "Miłgost",
    "Miłobąd",
    "Miłobor",
    "Miłobrat",
    "Miłochat",
    "Miłoczat",
    "Miłodrog",
    "Miłodziad",
    "Miłogost",
    "Miłorad",
    "Miłosław",
    "Miłostryj",
    "Miłosz",
    "Miłowan",
    "Miłowit",
    "Miłowuj",
    "Miłwit",
    "Minigniew",
    "Minogniew",
    "Mirogniew",
    "Mirogod",
    "Mironieg",
    "Mirosław",
    "Mirzęta",
    "Misław",
    "Mleko",
    "Młoka",
    "Modlibog",
    "Modliboż",
    "Mogiłek",
    "Mojmir",
    "Mojsław",
    "Morzysław",
    "Mrocław",
    "Mrocsław",
    "Mroczesław",
    "Mroczsław",
    "Mroczysław",
    "Mrosław",
    "Mszczuj",
    "Mszczujwoj",
    "Mścibor",
    "Mścigniew",
    "Mścisław",
    "Mściwoj",
    "Mściwuj",
    "Mysław",
    "Myślibor",
    "Myślidar",
    "Myślim",
    "Myślimir",
    "Nacław",
    "Nacsław",
    "Naczęmiar",
    "Naczęmier",
    "Naczęmir",
    "Naczęrad",
    "Naczęsław",
    "Naczęwoj",
    "Naczęwuj",
    "Nadar",
    "Nadbor",
    "Nadmir",
    "Nadziej",
    "Nagod",
    "Namir",
    "Namysław",
    "Nasiębąd",
    "Nasiębor",
    "Nasiębud",
    "Nasięgniew",
    "Nasław",
    "Nawoj",
    "Nawuj",
    "Nażyr",
    "Niebor",
    "Niebylec",
    "Niecisław",
    "Niedabył",
    "Niedabysz",
    "Niedalic",
    "Niedał",
    "Niedamir",
    "Niedan",
    "Niedaniec",
    "Niedoma",
    "Niedomysł",
    "Niedrog",
    "Niegodoma",
    "Niegosław",
    "Niegowoj",
    "Niegrod",
    "Nielubiec",
    "Niemierz",
    "Niemir",
    "Niemironieg",
    "Niemoj",
    "Niemst",
    "Niemsta",
    "Niemszczon",
    "Nienach",
    "Niepełka",
    "Nieprasz",
    "Nieproch",
    "Nieprosz",
    "Nieprzebąd",
    "Nieprzebud",
    "Nieprzebysz",
    "Nierad",
    "Niered",
    "Nierod",
    "Niesiebąd",
    "Niesiebor",
    "Niesiebud",
    "Niesiodł",
    "Niestek",
    "Niestoj",
    "Niesuł",
    "Nietęg",
    "Nietubył",
    "Niewsza",
    "Niezamysł",
    "Nieznamir",
    "Nieznawuj",
    "Ninogniew",
    "Ninomysł",
    "Ninosz",
    "Ninota",
    "Ninowłod",
    "Nowosiodł",
    "Objęsław",
    "Ocięsław",
    "Odolan",
    "Okrzesław",
    "Opoka",
    "Osiębor",
    "Osięgniew",
    "Ostrobod",
    "Ostrogniew",
    "Ostrowod",
    "Pakosław",
    "Pełczybog",
    "Pęcisław",
    "Pęcław",
    "Pęcsław",
    "Pękosław",
    "Pępik",
    "Pęsław",
    "Pomian",
    "Pomir",
    "Pomścibor",
    "Poznan",
    "Poznomir",
    "Pożar",
    "Prosimir",
    "Przebąd",
    "Przebor",
    "Przecław",
    "Przecsław",
    "Przedabog",
    "Przedbor",
    "Przedmir",
    "Przedpełk",
    "Przedpołk",
    "Przedsław",
    "Przedwoj",
    "Przedwor",
    "Przedwuj",
    "Przemęt",
    "Przemieł",
    "Przemił",
    "Przemir",
    "Przemysł",
    "Przemysław",
    "Przemyślibor",
    "Przesław",
    "Przezdoma",
    "Przezdziad",
    "Przezmir",
    "Przezpraw",
    "Przezprzem",
    "Przyboj",
    "Przybor",
    "Przybygniew",
    "Przybylut",
    "Przybymir",
    "Przybyrad",
    "Przybysław",
    "Przybysza",
    "Przybywoj",
    "Przybywuj",
    "Przysnobor",
    "Przywit",
    "Psar",
    "Racibor",
    "Raciborz",
    "Racigniew",
    "Racimiar",
    "Racimir",
    "Racisław",
    "Racław",
    "Racsław",
    "Radmir",
    "Radociech",
    "Radogost",
    "Radomiar",
    "Radomił",
    "Radomir",
    "Radosław",
    "Radost",
    "Radosz",
    "Radowan",
    "Radowit",
    "Radowuj",
    "Radsław",
    "Radsuł",
    "Radzan",
    "Radzim",
    "Rasław",
    "Ratsław",
    "Recibor",
    "Recław",
    "Recsław",
    "Redosław",
    "Redsław",
    "Resław",
    "Retsław",
    "Rocław",
    "Rocsław",
    "Rodomieł",
    "Rodomił",
    "Rodsław",
    "Rolirad",
    "Rosław",
    "Rościgniew",
    "Rościsław",
    "Rozniat",
    "Rozniata",
    "Rus",
    "Rzędzimir",
    "Rzędzisław",
    "Rzędziwoj",
    "Sambor",
    "Samogost",
    "Samosąd",
    "Sęczygniew",
    "Sędomir",
    "Sędosław",
    "Sędowin",
    "Sędowoj",
    "Sędzigrod",
    "Sędzimir",
    "Sędzisław",
    "Sędziwoj",
    "Sędziwuj",
    "Sędźwoj",
    "Sężyr",
    "Siabor",
    "Sidło",
    "Siebąd",
    "Siebor",
    "Sieciebor",
    "Sieciech",
    "Sieciesław",
    "Siecław",
    "Siecsław",
    "Siedlewit",
    "Siemar",
    "Siemidrog",
    "Siemierz",
    "Siemił",
    "Siemimił",
    "Siemimysł",
    "Siemir",
    "Siemirad",
    "Siemisław",
    "Siemmił",
    "Siemomysł",
    "Siemomysław",
    "Siemoradz",
    "Siemosław",
    "Siemowit",
    "Siepraw",
    "Sierosław",
    "Siesław",
    "Siestrzemił",
    "Siestrzewit",
    "Sietbor",
    "Sięgniew",
    "Siężyr",
    "Sirosław",
    "Sjęgniew",
    "Skamir",
    "Skarbimir",
    "Skarbimirz",
    "Skarbisław",
    "Skardmir",
    "Skaziczest",
    "Sławciech",
    "Sławobor",
    "Sławociech",
    "Sławomiar",
    "Sławomir",
    "Sławosław",
    "Słup",
    "Smagor",
    "Smarz",
    "Smysław",
    "Snowid",
    "Sobiebor",
    "Sobiemir",
    "Sobiemysł",
    "Sobierad",
    "Sobiesąd",
    "Sobiesław",
    "Sobieżyr",
    "Solisław",
    "Spycigniew",
    "Spycimir",
    "Spycisław",
    "Spyćmier",
    "Spyćmierz",
    "Spyćmir",
    "Stanibor",
    "Stanimir",
    "Stanisław",
    "Stasław",
    "Stogniew",
    "Stoigniew",
    "Stoisław",
    "Stojan Wygnan",
    "Stojgniew",
    "Stojsław",
    "Stomir",
    "Stosław",
    "Strach",
    "Strachomir",
    "Strogobor",
    "Strogomir",
    "Stronisław",
    "Strosław",
    "Strzałek",
    "Strzebor",
    "Strzecław",
    "Strzecsław",
    "Strzedziwoj",
    "Strzedzsław",
    "Strzesław",
    "Strzesz",
    "Strzeszko",
    "Strzeżymir",
    "Strzeżysław",
    "Sudywoj",
    "Sulibor",
    "Sulibrat",
    "Sulidziad",
    "Suligost",
    "Sulim",
    "Sulima",
    "Sulimiar",
    "Sulimir",
    "Sulirad",
    "Sulisław",
    "Sulistryj",
    "Suliwuj",
    "Sulmir",
    "Swar",
    "Swojsław",
    "Swosław",
    "Szabor",
    "Szczęsny",
    "Szczodr",
    "Szebor",
    "Szenbor",
    "Szydło",
    "Ścibor",
    "Świebąd",
    "Świebor",
    "Świeborz",
    "Świeciech",
    "Świecław",
    "Świedarg",
    "Świegniew",
    "Świelub",
    "Świemił",
    "Świemir",
    "Świerad",
    "Świesław",
    "Święcesław",
    "Święcsław",
    "Święsław",
    "Świętobor",
    "Świętomir",
    "Świętopełk",
    "Świętosław",
    "Świrad",
    "Świrszcz",
    "Taniebor",
    "Tasław",
    "Tatomier",
    "Tatomir",
    "Tatumir",
    "Tęgomir",
    "Toligniew",
    "Tolisław",
    "Tomił",
    "Tomir",
    "Tomisław",
    "Tosław",
    "Trup",
    "Trzebiebor",
    "Trzebiegost",
    "Trzebiemiar",
    "Trzebiemier",
    "Trzebiemir",
    "Trzebiemysł",
    "Trzebiesław",
    "Trzebisław",
    "Trzebomysł",
    "Trzebor",
    "Trzebowit",
    "Twardomir",
    "Twardosław",
    "Twardostoj",
    "Tworzymir",
    "Tworzysław",
    "Ubysław",
    "Uchacz",
    "Uniebog",
    "Unieboż",
    "Uniedrog",
    "Uniegost",
    "Uniemir",
    "Uniemysł",
    "Unierad",
    "Uniesław",
    "Uniewit",
    "Unieżyr",
    "Unimir",
    "Unirad",
    "Unisław",
    "Uściwoj",
    "Wacław",
    "Warcisław",
    "Warcsław",
    "Warsław",
    "Wędziemir",
    "Wicław",
    "Wicsław",
    "Wielebor",
    "Wielebyt",
    "Wieledrog",
    "Wielesław",
    "Wielimir",
    "Wielisław",
    "Wielsław",
    "Wiercisław",
    "Wiesław",
    "Więcemiar",
    "Więcemier",
    "Więcemił",
    "Więcemir",
    "Więcerad",
    "Więcesław",
    "Więcław",
    "Więcmier",
    "Więcsław",
    "Więsław",
    "Wilczan",
    "Wilczęta",
    "Wilk",
    "Wilkomir",
    "Wirciżyr",
    "Wirzchosław",
    "Wisław",
    "Witan",
    "Witomir",
    "Witomysł",
    "Witosław",
    "Witosz",
    "Witsław",
    "Władysław",
    "Właścibor",
    "Włocław",
    "Włocsław",
    "Włodzimierz",
    "Włodzimir",
    "Włodzisław",
    "Włościbor",
    "Włościbyt",
    "Włościwoj",
    "Wociech",
    "Wojan",
    "Wojbor",
    "Wojciech",
    "Wojemił",
    "Wojesław",
    "Wojisław",
    "Wojmir",
    "Wojsław",
    "Wolebor",
    "Wolemir",
    "Wolimir",
    "Wolisław",
    "Wolmir",
    "Wolrad",
    "Wosław",
    "Wrocisław",
    "Wrociwoj",
    "Wrocsław",
    "Wrosław",
    "Wszabor",
    "Wszebąd",
    "Wszebor",
    "Wszeborz",
    "Wszeciech",
    "Wszegniew",
    "Wszemiar",
    "Wszemił",
    "Wszemir",
    "Wszemysł",
    "Wszerad",
    "Wszesiodł",
    "Wszesuł",
    "Wszetopełk",
    "Wświebor",
    "Wysław",
    "Wyszabor",
    "Wyszebor",
    "Wyszemir",
    "Wyszesław",
    "Wyszetrop",
    "Wyszomir",
    "Wyszymir",
    "Zadar",
    "Zamir",
    "Zawisza",
    "Zbelut",
    "Zbigniew",
    "Zbrosław",
    "Zbygniew",
    "Zbyhniew",
    "Zbylut",
    "Zbysław",
    "Zbywoj",
    "Zdamir",
    "Zdawuj",
    "Zdzibor",
    "Zdziczest",
    "Zdziebąd",
    "Zdziebor",
    "Zdziebud",
    "Zdziegod",
    "Zdziegrod",
    "Zdziemił",
    "Zdziemir",
    "Zdzierad",
    "Zdziesław",
    "Zdziesuł",
    "Zdziewit",
    "Zdziewuj",
    "Zdzigod",
    "Zdzigrod",
    "Zdzimir",
    "Zdzisław",
    "Zdzistryj",
    "Zdziwoj",
    "Zdziwuj",
    "Ziemomysł",
    "Ziemowit",
    "Znamir",
    "Zwnisław",
    "Żaba",
    "Żałoba",
    "Żegota",
    "Żelibor",
    "Żelibrat",
    "Żelidrag",
    "Żeligniew",
    "Żelimysł",
    "Żelisław",
    "Żelistryj",
    "Żeliwuj",
    "Żerosław",
    "Żuk",
    "Żur",
    "Żyła",
    "Żyłka",
    "Żyrosław",
  ],
};


export const maleLatinNames = {
  type: "picker",
  list: [
    "Agrippa",
    "Amulius",
    "Ancus",
    "Appius",
    "Arruns",
    "Attius",
    "Aule",
    "Aulus",
    "Cae",
    "Caeles",
    "Caelus",
    "Caeso",
    "Camillus",
    "Canus",
    "Cneve",
    "Cossus",
    "Decimus",
    "Decius",
    "Drusus",
    "Faustus",
    "Flavius",
    "Gaius",
    "Gallus",
    "Gnaeus",
    "Herius",
    "Hostus",
    "Karcuna",
    "Larce",
    "Laris",
    "Lucius",
    "Mamercus",
    "Manius",
    "Marce",
    "Marcellus",
    "Marcus",
    "Marius",
    "Maximus",
    "Metie",
    "Mettius",
    "Minatus",
    "Minius",
    "Nerius",
    "Nero",
    "Nonus",
    "Novius",
    "Numa",
    "Numerius",
    "Octavius",
    "Olus",
    "Opiter",
    "Oppius",
    "Ovius",
    "Paccius",
    "Paullus",
    "Paulus",
    "Pompo",
    "Postumus",
    "Potitus",
    "Primus",
    "Proclus",
    "Proculus",
    "Publius",
    "Quintus",
    "Salvius",
    "Secundus",
    "Seppius",
    "Septimus",
    "Sertor",
    "Servius",
    "Sextus",
    "Silvanus",
    "Sisenna",
    "Spurius",
    "Statius",
    "Taurus",
    "Tertius",
    "Tiberius",
    "Titus",
    "Trebius",
    "Tullus",
    "Vettius",
    "Vibius",
    "Volesus",
    "Vopiscus",
  ],
};
export const maleRussianNames = {
  type: "picker",
  list: [
    "Abagor",
    "Abamon",
    "Abataly",
    "Abelyar",
    "Abid",
    "Abily",
    "Abnody",
    "Abram",
    "Aburom",
    "Adam",
    "Afanasy",
    "Agafangel",
    "Agafodor",
    "Agafon",
    "Agafonik",
    "Agafopod",
    "Agafopus",
    "Agap",
    "Agapion",
    "Agapit",
    "Agapy",
    "Agat",
    "Agav",
    "Agavva",
    "Albert",
    "Alexander",
    "Alexey",
    "Amvrosy",
    "Anatoly",
    "Andrei",
    "Andrey",
    "Anton",
    "Arkadiy",
    "Arkady",
    "Artemy",
    "Artyom",
    "Artyom",
    "Avda",
    "Avdakt",
    "Avdelay",
    "Avdey",
    "Avdifaks",
    "Avdiky",
    "Avdiyes",
    "Avdon",
    "Avel",
    "Avenir ",
    "Aventin ",
    "Averky",
    "Avgar",
    "Avgury",
    "Avgust",
    "Avgustin",
    "Avian ",
    "Avim ",
    "Avimelekh",
    "Avip",
    "Avit",
    "Aviv",
    "Avksenty",
    "Avksily",
    "Avksivy",
    "Avkt",
    "Avram ",
    "Avrelian",
    "Avrely",
    "Avrey",
    "Avros",
    "Avsey",
    "Avtonom",
    "Avudim",
    "Avundy",
    "Avva",
    "Avvakir",
    "Avvakum ",
    "Bogdan",
    "Boris ",
    "Budimir",
    "Daniel",
    "Daniil",
    "Danila ",
    "David ",
    "Denis ",
    "Dmitry",
    "Eduard ",
    "Elisei",
    "Fedot",
    "Feofan",
    "Fyodor",
    "Gavriil",
    "Gennady",
    "Genrikh",
    "Georgy ",
    "Gerasim",
    "German ",
    "Gleb",
    "Grigory",
    "Grischa",
    "Ignat",
    "Ilarion",
    "Ilya",
    "Iosif",
    "Ivan",
    "Jaroslav",
    "Kirill",
    "Kliment",
    "Kolya",
    "Konstantin",
    "Lavrentiy",
    "Lev",
    "Leonid",
    "Lev ",
    "Pyotr",
    "Lukyan",
    "Matvei",
    "Maxim ",
    "Miron ",
    "Mstislav ",
    "Nectarios",
    "Nikita ",
    "Nikola",
    "Nikolay",
    "Oleg",
    "Osip",
    "Ossip",
    "Panteleimon",
    "Pavel",
    "Pavsikakiy",
    "Prokhor",
    "Prokopy",
    "Ratimir",
    "Rodion",
    "Roman ",
    "Rostislav ",
    "Ruslan ",
    "Sasha ",
    "Simeon",
    "Simon ",
    "Slava ",
    "Stanislav ",
    "Stepan ",
    "Svetoslav",
    "Sviatoslav",
    "Tikhon",
    "Timofey",
    "Timur ",
    "Trifon",
    "Trofim",
    "Vadim",
    "Valentin",
    "Valery",
    "Vasily",
    "Veniamin",
    "Victor ",
    "Vitalii",
    "Vladilen",
    "Vladimir ",
    "Vladislav",
    "Vsevolod",
    "Vyacheslav",
    "Yakov",
    "Yaroslav",
    "Yefim",
    "Yegor",
    "Yermolay",
    "Yevgeny",
    "Yury",
    "Zakhar",
    "Zinovy",
  ],
};

export const maleGaelicNames = {
  type: "picker",
  list: [
    //Scottish Gaelic male given names
    "Làmhaich",
    "Adaidh",
    "Adhamh",
    "Àdhamh",
    "Ailbeart",
    "Ailean",
    "Ailig",
    "Ailpean",
    "Ailpein",
    "Aindrea",
    "Aindreas",
    "Alasdair",
    "Amhladh",
    "Amhlaibh",
    "Amhlaidh",
    "Amhlaigh",
    "Angaidh",
    "Anndra",
    "Anndrais",
    "Aodh",
    "Aodhàn",
    "Aonghas",
    "Aonghus",
    "Arailt",
    "Artair",
    "Artur",
    "Asgall",
    "Baltair",
    "Bearnard",
    "Beathan",
    "Beistean",
    "Benneit",
    "Bhaltair",
    "Bhatair",
    "Brian",
    "Cailean",
    "Calum",
    "Caomhainn",
    "Cathal",
    "Ciaran",
    "Cliamain",
    "Coinneach",
    "Còiseam",
    "Colla",
    "Colum Cille",
    "Comhnall",
    "Conall",
    "Conn",
    "Coraidh",
    "Cormac",
    "Cormag",
    "Crìsdean",
    "Cuithbeart",
    "Daibhidh",
    "Dàibhidh",
    "Daidh",
    "Dànaidh",
    "Daniel",
    "Deorsa",
    "Deòrsa",
    "Diarmad",
    "Domhnall",
    "Dòmhnall",
    "Domhnull",
    "Dòmhnull",
    "Donaidh",
    "Donnchadh",
    "Dubh",
    "Dubhghall",
    "Dubh-shìth",
    "Dùghall",
    "Dùghlas",
    "Eachann",
    "Eacharn",
    "Eairdsidh",
    "Ealar",
    "Eanraig",
    "Eanruig",
    "Edelret",
    "Eideard",
    "Eirdsidh",
    "Ellair",
    "Eòghan",
    "Eòghann",
    "Eòin",
    "Eòsaph",
    "Eumann",
    "Faolan",
    "Fearchar",
    "Fearghas",
    "Filib",
    "Fionn",
    "Fionnghall",
    "Fionnghan",
    "Fionnlagh",
    "Frang",
    "Frangan",
    "Frangean",
    "Friseal",
    "Gille-Aindreis",
    "Gilleasbaig",
    "Gilleasbuig",
    "Gill-easbuig",
    "Gill-Eathain",
    "Gillebeart",
    "Gillebrìde",
    "Gille-Brìdhde",
    "Gille-Caluim",
    "Gille-Crìosd",
    "Gill-Eòin",
    "Gill-Iosa",
    "Gillìosa",
    "Goiridh",
    "Goraidh",
    "Gòrdan",
    "Grannd",
    "Greum, Greumach",
    "Griogair",
    "Guaidre",
    "Harailt",
    "Harsain",
    "Hòmair",
    "Horas",
    "Hùisdean",
    "Iàcob",
    "Iagan",
    "Iain",
    "Ianatan",
    "Iomhair",
    "Iomhar",
    "Iòna",
    "Iosag",
    "Iòsaph",
    "Labhrainn",
    "Labhruinn",
    "Lachlann",
    "Lamhaich",
    "Laomann",
    "Leanaidh",
    "Leannain",
    "Leodhas",
    "Leòmhannàrd",
    "Lùcas",
    "Luthais",
    "Mànas",
    "Mànus",
    "Maoilios",
    "Maol-Chaluim",
    "Maol-Domhnuich",
    "Maol-Dòmhnuich",
    "Maoldònaich",
    "Maol-Iosa",
    "Maolmhuire",
    "Maol-Moire",
    "Maolruibh",
    "Marc",
    "Marcas",
    "Martainn",
    "Màrtainn",
    "Mata",
    "Mìcheal",
    "Micheil",
    "Mìcheil",
    "Morgan",
    "Muireach",
    "Munga",
    "Mungan",
    "Murchadh",
    "Neacal",
    "Neachdainn",
    "Niall",
    "Niallghus",
    "Odaiseis",
    "Oilbhreis",
    "Oisean",
    "Pàdair",
    "Padean",
    "Pàdraig",
    "Pàdruig",
    "Pàl",
    "Para",
    "Pàra",
    "Pàrlan",
    "Peadair",
    "Peadar",
    "Peadaran",
    "Peadrus",
    "Pòl",
    "Prainnseas",
    "Raghnall",
    "Raibeart",
    "Ràild",
    "Raonull",
    "Ringean",
    "Risteard",
    "Rob",
    "Roibeart",
    "Ronain",
    "Ruairidh",
    "Ruaraidh",
    "Ruaridh",
    "Ruiseart",
    "Sachairi",
    "Samuel",
    "Sandaidh",
    "Seaghdh",
    "Seàrlas",
    "Seathan",
    "Seoc",
    "Seocan",
    "Seonaidh",
    "Seoras",
    "Seòras",
    "Seòsaidh",
    "Seumas",
    "Sgàire",
    "Sim",
    "Sìm",
    "Simidh",
    "Sìomon",
    "Solamh",
    "Somhairle",
    "Steafan",
    "Stiùbhard",
    "Stiùbhart",
    "Tadhg",
    "Tamhas",
    "Tàmhas",
    "Taog",
    "Tasgall",
    "Tearlach",
    "Teàrlach",
    "Tiobaid",
    "Tòmachan",
    "Tomag",
    "Tomaidh",
    "Tòmas",
    "Torcadall",
    "Torcall",
    "Torcull",
    "Tormod",
    "Tormoid",
    "Uailean",
    "Ualan",
    "Ualraig",
    "Uarraig",
    "Uilleachan",
    "Uilleam",
    "Uisdean",
    "Ùisdean",
    //Native Irish male given names
    "Abbán",
    "Aibhne",
    "Ailín",
    "Ailbhe",
    "Ailill",
    "Ainníleas",
    "Amhalgaidh",
    "Anluan",
    "Anmchadh",
    "Aodh",
    "Aodhán",
    "Aogán",
    "Aodhagán",
    "Aonghus",
    "Árdghal",
    "Ardghal",
    "Ardghar",
    "Art",
    "Barra",
    "Bairre",
    "Bearach",
    "Baothghalach",
    "Beacán",
    "Bearchán",
    "Bran",
    "Breasal",
    "Breandán",
    "Breanndán",
    "Bréanainn",
    "Brian",
    "Brochadh",
    "Buadhach",
    "Cailean",
    "Coilean",
    "Coileán",
    "Coilín",
    "Cuileán",
    "Cairbre",
    "Calbhach",
    "Caoimhín",
    "Caoimhghín",
    "Caolán",
    "Caomhán",
    "Carraig",
    "Cárthach",
    "Cathal",
    "Cathaoir",
    "Cathbharr",
    "Ceallach",
    "Ceallachán",
    "Cearbhall",
    "Cían",
    "Cíanán",
    "Ciarán",
    "Cinnéididh",
    "Cinnéidigh",
    "Cionaodh",
    "Ciothruadh",
    "Cillian",
    "Coinneach",
    "Cainneach",
    "Coireall",
    "Colla",
    "Colm",
    "Colum",
    "Colmán",
    "Comán",
    "Comhghall",
    "Comhghan",
    "Conall",
    "Conán",
    "Conaire",
    "Conchúr",
    "Conchobhar",
    "Conchubhar",
    "Conghalach",
    "Conmhac",
    "Conn",
    "Connla",
    "Connlaodh",
    "Cormac",
    "Cosnamhach",
    "Criomthann",
    "Cróchán",
    "Crónán",
    "Cuan",
    "Cúchonnacht",
    "Cuimín",
    "Cúmhaighe",
    "Cúmheadha",
    "Dabhag",
    "Dabhóg",
    "Daibhí",
    "Dáithí",
    "Damháin",
    "Dara",
    "Dáire",
    "Daire",
    "Déaglán",
    "Deaglán",
    // "Deasmhumhnach",
    "Diarmaid",
    "Diarmuid",
    "Diarmait",
    "Dónall",
    "Dónal",
    "Domhnall",
    "Donn",
    "Donnán",
    "Donnghaile",
    "Donnchadh",
    "Donnchadha",
    "Dubhaltach",
    "Dubhán",
    "Dubhghall",
    "Dubhghlas",
    "Dúnlang",
    "Eachaidh",
    "Eachann",
    "Eachdhonn",
    "Eachthighearn",
    "Éanán",
    "Éanna",
    "Éinde",
    "Earcán",
    "Earnán",
    "Eirnín",
    "Éibhear",
    "Éignach",
    "Eignach",
    "Éigneachán",
    "Eigneachán",
    "Éimhín",
    "Éireamhón",
    "Eireamhón",
    "Eireamhán",
    "Eochaidh",
    "Eoghan",
    "Eoghainín",
    "Fachtna",
    "Fáilbhe",
    "Faolán",
    "Fearadhach",
    "Fearchar",
    "Feardorcha",
    "Fearganainm",
    "Fearghal",
    "Feichín",
    "Féilim",
    "Feidhlim",
    "Fergus",
    "Feargus",
    "Fearghus",
    "Fiach",
    "Fiacha",
    "Fiachra",
    "Finghin",
    "Fionghuine",
    "Fionn",
    "Finn",
    "Fionntán",
    "Finnian",
    "Fionnbharr",
    "Fitheal",
    "Flann",
    "Flannán",
    "Garbhán",
    "Glaisne",
    "Iarlaith",
    "Iarfhlaith",
    "Irial",
    "Lachtna",
    "Laoiseach",
    "Laoighseach",
    "Lasairian",
    "Lochlann",
    "Lochlainn",
    "Lomán",
    "Lonán",
    "Lorcán",
    "Lughaidh",
    "Maeleachlainn",
    "Maelsheachlainn",
    "Maelíosa",
    "Mainchín",
    "Maodhóg",
    "Maoilín",
    "Maoilir",
    "Maolcholm",
    "Maolcholuim",
    "Maolmórdha",
    "Maolmhuire",
    "Maolruadháin",
    "Marcus",
    "Mathghamhain",
    "Muircheartach",
    "Muireadhach",
    "Muireach",
    "Muirgheas",
    "Muiris",
    "Murchadh",
    "Naomhán",
    "Naoise",
    "Naos",
    "Neachtan",
    "Neasán",
    "Niall",
    "Niallán",
    "Nollaig",
    "Odhrán",
    "Oireachtach",
    "Oisín",
    "Oscar",
    "Riain",
    "Roibhilín",
    "Raibhilín",
    "Ruibhilín",
    "Rónán",
    "Ros",
    "Ruadhán",
    "Ruairí",
    "Ruaidhrí",
    "Ruaridh",
    "Saerbhreathach",
    "Sechnassach",
    "Seachnasach",
    "Séadna",
    "Senán",
    "Siadhal",
    "Siaghal",
    "Sioda",
    "Suibhne",
    "Tadhg",
    "Taichleach",
    "Tighernach",
    "Tighearnán",
    "Tiarnach",
    "Tiarnán",
    "Toirdhealbhach",
    "Toirleach",
    "Torna",
    "Treabhair",
    "Tuathal",
    "Uaitéar",
    "Uaithne",
    "Ualgharg",
    "Ultán",
    "Ultan",
  ],
};

export const WHFMaleHumanNames = {
  type: "picker",
  list: [
    "Abelhard",
    "Abelhelm",
    "Admund",
    "Adred",
    "Adric",
    "Agis",
    "Alaric",
    "Alberic",
    "Albrecht",
    "Aldebrand",
    "Aldred",
    "Aldric",
    "Alfreid",
    "Alric",
    "Altmar",
    "Andre",
    "Andred",
    "Andric",
    "Anselhelm",
    "Anton",
    "Arne",
    "Arnulf",
    "Axel",
    "Axelbrand",
    "Baldred",
    "Baldric",
    "Baldwin",
    "Balthasar",
    "Barnabas",
    "Bart",
    "Bartolf",
    "Bartomar",
    "Bernolt",
    "Bertold",
    "Bertolf",
    "Boris",
    "Bruno",
    "Burgolf",
    "Calvin",
    "Casimir",
    "Caspar",
    "Cedred",
    "Conrad",
    "Corvin",
    "Dagmar",
    "Dankmar",
    "Dankred",
    "Dekmar",
    "Detlef",
    "Diebold",
    "Diel",
    "Dieter",
    "Dietfried",
    "Dietmar",
    "Dietmund",
    "Dietrich",
    "Dirk",
    "Donat",
    "Durnhelm",
    "Eber",
    "Eckel",
    "Eckhart",
    "Edgar",
    "Edmund",
    "Edwin",
    "Ehrhart",
    "Ehrl",
    "Ehrwig",
    "Eldred",
    "Elmeric",
    "Emil",
    "Engel",
    "Engelbert",
    "Engelbrecht",
    "Engelhart",
    "Eodred",
    "Eomund",
    "Erasmus",
    "Erdman",
    "Erdred",
    "Erich",
    "Erkenbrand",
    "Erman",
    "Ernst",
    "Erwin",
    "Eugen",
    "Eustasius",
    "Ewald",
    "Fabian",
    "Faustus",
    "Felix",
    "Ferdinand",
    "Fleugweiner",
    "Fosten",
    "Franz",
    "Frediger",
    "Fredric",
    "Friebald",
    "Friedrich",
    "Fulko",
    "Gawin",
    "Gerber",
    "Gerhart",
    "Gerlach",
    "Gernar",
    "Gerolf",
    "Gilbrecht",
    "Gisbert",
    "Giselbrecht",
    "Gismar",
    "Goran",
    "Gosbert",
    "Goswin",
    "Gotfried",
    "Gothard",
    "Gottolf",
    "Gotwin",
    "Gregor",
    "Greimold",
    "Grimwold",
    "Griswold",
    "Guido",
    "Gundolf",
    "Gundred",
    "Gunnar",
    "Gunter",
    "Gunther",
    "Gustaf",
    "Hadred",
    "Hadwin",
    "Hagar",
    "Hagen",
    "Haldred",
    "Halman",
    "Hamlyn",
    "Hans",
    "Harbrand",
    "Harman",
    "Hartmann",
    "Haug",
    "Heidric",
    "Heimar",
    "Heinfried",
    "Heinman",
    "Heinrich",
    "Heinz",
    "Helmut",
    "Henlyn",
    "Hermann",
    "Herwin",
    "Hieronymus",
    "Hildebart",
    "Hildebrand",
    "Hildemar",
    "Hildemund",
    "Hildred",
    "Hildric",
    "Horst",
    "Hugo",
    "Igor",
    "Ingwald",
    "Jander",
    "Jekil",
    "Jodokus",
    "Johann",
    "Jonas",
    "Jorg",
    "Jorn",
    "Josef",
    "Jost",
    "Jurgen",
    "Karl",
    "Kaspar",
    "Klaus",
    "Kleber",
    "Konrad",
    "Konradin",
    "Kurt",
    "Lamprecht",
    "Lanfried",
    "Lanric",
    "Lanwin",
    "Leo",
    "Leopold",
    "Levin",
    "Liebert",
    "Liebrecht",
    "Liebwin",
    "Lienhart",
    "Linus",
    "Lodwig",
    "Lothar",
    "Lucius",
    "Ludwig",
    "Luitpold",
    "Lukas",
    "Lupold",
    "Lupus",
    "Luther",
    "Lutolf",
    "Madred",
    "Magnus",
    "Mandred",
    "Manfred",
    "Mathias",
    "Max",
    "Maximillian",
    "Meiner",
    "Meinhart",
    "Meinolf",
    "Mekel",
    "Merkel",
    "Nat",
    "Nathandar",
    "Nicodemus",
    "Odamar",
    "Odric",
    "Odwin",
    "Olbrecht",
    "Oldred",
    "Oldric",
    "Ortlieb",
    "Ortolf",
    "Osric",
    "Oswald",
    "Oswin",
    "Otfried",
    "Otto",
    "Otwin",
    "Owin",
    "Paulus",
    "Prospero",
    "Ragen",
    "Ralf",
    "Rambrecht",
    "Ranald",
    "Randulf",
    "Ranulf",
    "Reikhard",
    "Rein",
    "Reiner",
    "Reinhard",
    "Reinolt",
    "Reuban",
    "Rigo",
    "Roderic",
    "Rolf",
    "Ruben",
    "Rudel",
    "Rudgar",
    "Rudolf",
    "Rufus",
    "Ruprecht",
    "Sebastian",
    "Semund",
    "Sepp",
    "Sieger",
    "Siegfried",
    "Siegmund",
    "Sigismund",
    "Sigric",
    "Steffan",
    "Tankred",
    "Theoderic",
    "Tilmann",
    "Tomas",
    "Trubald",
    "Trubert",
    "Udo",
    "Ulfman",
    "Ulfred",
    "Ulli",
    "Ulman",
    "Uto",
    "Valdred",
    "Valdric",
    "Varl",
    "Viggo",
    "Viktor",
    "Vilmar",
    "Volker",
    "Volkhard",
    "Volkin",
    "Volkrad",
    "Voltz",
    "Walbrecht",
    "Waldor",
    "Waldred",
    "Walther",
    "Warmund",
    "Werner",
    "Wilbert",
    "Wilfried",
    "Wilhelm",
    "Woldred",
    "Wolfgang",
    "Wolfhart",
    "Wolfram",
    "Wulf",
    "Xavier",

    //non whfrp
    "Gebhard",
    "Widekind",
    "Bertram"
  ],
};

export const wizardsAndClerics = {
  type: "picker",
  list: [
    "Absalom", "Adompha", "Afgorkon", "Akivasha", "Alcemides", 
    "Anector", "Anuradhapura", "Argaphrax", "Argelibichus", "Ariadne", 
    "Azgelasgus", "Baithorion", "Bypeld", "Calindonadrius", "Caliph", 
    "Cardoxicus", "Chongrilar", "Dagozai", "Darunzadar", "Draupnir", 
    "Dweb", "Dwerulas", "Ebanoose", "Ebbonly", "Eibur", 
    "Erasmus", "Galendil", "Habruztish", "Hadrathus", "Hekkador", 
    "Ib", "Ildawir", "Iminix", "Iomagoth", "Iquanux", 
    "Ishgadona", "Izdrel", "Jaspondar", "Khumbanigesh", "Leniqua", 
    "Llambichus", "Maal", "Marquanos", "Matai", "Mewick", 
    "Mhu", "Moloch", "Nambaloth", "Naroob", "Nichiddor", 
    "Nimed", "Ningorus", "Norovus", "Okar", "Olloothy", 
    "Orastes", "Oryx", "Palamabron", "Pergamoy", "Pharnoc", 
    "Phenquor", "Philisia", "Polarion", "Ptarth", "Quilian", 
    "Rom", "Salome", "Sarnath", "Scarabus", "Shang", 
    "Somiator", "Sotar", "Talu", "Thankarol", "Thasaidon", 
    "Theotormon", "Thulan", "Thulsa", "Tsanth", "Tspo", 
    "Tutothmes", "Uldor", "Urizen", "Vala", "Valbroso", 
    "Vallardine", "Vathek", "Veezi", "Volphotux", "Vyldabec", 
    "Waxenesi", "Weekapaug", "Xaltotun", "Xergal", "Zapranoth", 
    "Zelthura", "Ziroonderel", "Zorathus", "Zordanir", "Zotulla"
  ]
}

export const warriorsAndThieves = {
  type: "picker",
  list: [
    "Akurion", "Alveric", "Amalric", "Angarth", "Anuk", 
    "Aram", "Argosa", "Athelstane", "Camballio", "Carmac", 
    "Cashius", "Cathfytz", "Cerngoth", "Cobart", "Constantius", 
    "Cormoran", "Cromlek", "Cushara", "Cyntrom", "Segovian", 
    "Dugar", "Evadare", "Faraad", "Ganelon", "Ghor", 
    "Gondelor", "Gug", "Harnam", "Hoaraph", "Istrobian", 
    "Jadawin", "Japthon", "Jeddak", "Kadatheron", "Kalikalides", 
    "Kerkadel", "Khavran", "Kishtu", "Kothar", "Krallides", 
    "Kulan", "Lanom", "Llulch", "Loden", "Maldivius", 
    "Matsognir", "Minoc", "Mocair", "Morghi", "Mors", 
    "Nerelon", "Noureddin", "Oberon", "Oggon", "Ominor", 
    "Ommum-vog", "Ompallios", "Orillibus", "Pallantides", "Pallensus", 
    "Poliarion", "Prospero", "Publio", "Rannok", "Rolff", 
    "Sabdon", "Satampra", "Scaviolus", "Sigur", "Simban", 
    "Skafloc", "Smelroth", "Snish", "Sotar", "Tabernay", 
    "Tamash", "Tarascus", "Tardos", "Thekk", "Theseus", 
    "Thremnim", "Thulan", "Thuvan", "Thyl", "Tirouv", 
    "Tonunt", "Tortha", "Tredegar", "Turmus", "Ujuk", 
    "Valannus", "Vanator", "Vixeela", "Yachpina", "Zobol"
  ]
}
export const fantasticCreatures = {
    type: "picker",
    list: [
    "Abathon", "Ahriman", "Alagraada", "Anana", "Ang'qua'iash", 
    "Aphelis", "Ariston", "Astreas", "Athle", "Atost-rad", 
    "Avalonia", "Ayodhya", "Bashan", "Becar", "Brytoraugh", 
    "Carthoris", "Chemnis", "Chiron", "Chorondzon", "Chryseis", 
    "Djebel", "Dwalka", "Enion", "Erohye", "Fryx", 
    "Ganebon", "Gathol", "Gelka", "Gonlex", "Gothan", 
    "Haade", "Haalor", "Hadrubar", "Hoje", "Horphe", 
    "Hruengar", "Ilarnek", "Ishtar", "Ispazar", "Kajak", 
    "Kerim", "Kryth", "Kuruz", "Lirazel", "Lobon", 
    "Mandilip", "Marentina", "Memphor", "Mhu", "Mikaded", 
    "Mindus", "Modeca", "Mornoth", "Murcot", "Namirrha", 
    "Nimer", "Nouph", "Opphus", "Ouphaloc", "Phlesco", 
    "Pithaim", "Pommernar", "Puthuum", "Quamosmor", "Rakeban", 
    "Rayat-hin", "Rhyl", "Salensus", "Selestor", "Sindri", 
    "Skel'danu", "Slioma", "Sythaz", "Tarkas", "Tharmas", 
    "Threl", "Thuloneah", "Tilutan", "Ulassa", "Vandacia", 
    "Vandy", "Voormish", "Votalp", "Xicarph", "Xorex", 
    "Yandro", "Ydheem", "Yhoundeh", "Zdim", "Zenobia", 
    "Zokkar", "Zermish", "Zehbeh"
  ]
}
export const humanoids = {
    type: "picker",
    list: [
    "Agzan", "Arwoor", "Athbelny", "Atzul", "Beloso", 
    "Bokrug", "Bunda", "Chand", "Chuu", "Cykranosh", 
    "Dejah", "Domnos", "Eibon", "Emumen", "Eumar", 
    "Feethos", "Galan", "Gazal", "Gebal", "Glosoli", 
    "Gobir", "Goromé", "Grox", "Guhic", "Gurko", 
    "Hoom", "Iblix", "Iqqua", "Ischiros", "Jargo", 
    "Kalu", "Kordofo", "Krug", "Kuruz", "Loford", 
    "Loischa", "Manus", "Mnar", "Naat", "Nargis", 
    "Narl", "Narthos", "Nehic", "Niemm", "Obexah", 
    "Og", "Olgerd", "Oth", "Peshkhauri", "Pnoth", 
    "Quanga", "Rafe", "Rika", "Rintrak", "Rokol", 
    "Romm", "Roska", "Rubalsa", "Sakumbe", "Shull", 
    "Sorar", "Storbon", "Sybaros", "Taramus", "Tars", 
    "Tasarith", "Teelen", "Tewk", "Thaug", "Tinarath", 
    "Uccastrog", "Ummaos", "Unggo", "Urukush", "Usk", 
    "Vand", "Vetch", "Vladisav", "Vulpanomi", "Wixthor", 
    "Ydheem", "Zdim", "Zorathus", "Zordanir", "Zotulla",

    "Ylem", "Zaurak"
  ]
}


export const feminineElfNames = {
   type: "picker",
    list: [
    "Amarië",
    "Anairë",
    "Aredhel",
    "Celebrían",
    "Eärwen",
    "Eldalótë",
    "Elenwë",
    "Findis",
    "Finduilas",
    "Galadriel",
    "Nimloth",
    "Enelyë",
    "Idril",
    "Iminyë",
    "Indis",
    "Irimë",
    "Lúthien",
    "Míriel",
    "Mithrellas",
    "Nellas",
    "Nerdanel",
    "Nimrodel",

    "Eärwen",
    "Tatië"
    
  ]
}

export const masculineElfNames = {
    type: "picker",
    list: [
    "Corellian",
    "Aegnor",
    "Amdír",
    "Amras",
    "Amrod",
    "Amroth",
    "Angrod",
    "Argon",
    "Beleg",
    "Caranthir",
    "Celeborn",
    "Celebrimbor",
    "Celegorm",
    "Círdan",
    "Curufin",
    "Daeron",
    "Denethor",
    "Duilin",
    "Ecthelion",
    "Edrahil",
    "Egalmoth",
    "Elemmakil",
    "Elu Thingol",
    "Elmo",
    "Elrond",
    "Enel",
    "Enerdhil",
    "Eöl",
    "Erestor",
    "Fëanor",
    "Finarfin",
    "Fingolfin",
    "Fingon",
    "Finrod",
    "Felagund",
    "Finwë",
    "Galadhon",
    "Galathil",
    "Galdor",
    "Galdor",
    "Galion",
    "Gildor Inglorion",
    "Inglorion",
    "Gildor",
    "Gil-galad",
    "Gimli",
    "Glorfindel",
    "Gwindor",
    "Haldir",
    "Imin",
    "Inglor",
    "Ingwë",
    "Ingwion",
    "Legolas",
    "Lindir",
    "Mablung",
    "Maedhros",
    "Maeglin",
    "Maglor",
    "Mahtan",
    "Amroth",
    "Olwë",
    "Elwë",
    "Elmo",
    "Orodreth",
    "Oropher",
    "Thranduil",
    "Legolas",
    "Orophin",
    "Rúmil",
    "Lórien",
    "Haldir",
    "Pengolodh",
    "Penlod",
    "Quennar",
    "Onótimo",
    "Tirion",
    "Saeros",
    "Salgant",
    "Turgon",
    "Tuor",
    "Voronwë"
  ]
}

export const masculineTharkianNames = {
  type: "picker",
  list: [  "Azrik", "Hamilkar", "Balhan", "Zarqon", "Meskalon", "Jadhem", "Safir", "Hasdrubal", "Motep", "Serpin", 
  "Belashar", "Malqar", "Kamon", "Hannib", "Sabrak", "Tukar", "Barakesh", "Malzim", "Tibun", "Korabel", 
  "Zimran", "Selkar", "Uthil", "Ashkar", "Baalher", "Ezraq", "Zibran", "Adzubar", "Hirbal", "Lokmen", 
  "Murdan", "Ashbel", "Zartan", "Samirak", "Nabtel", "Fezzir", "Mastan", "Irdan", "Hamirak", "Gelash", 
  "Salnur", "Tamarik", "Iraman", "Tarkun", "Mozar", "Adzhel", "Samblar", "Sherifon", "Moltan", "Kurban", 
  "Astamar", "Bedrun", "Irsheb", "Jendrik", "Luthar", "Dakim", "Hirkal", "Neberan", "Farzal", "Nashim", 
  "Baratun", "Koshir", "Abilar", "Tarik", "Kelmar", "Zumdal", "Althir", "Fenrak", "Mishen", "Arganis", 
  "Karmil", "Yazkan", "Bashan", "Albelzar", "Zinar", "Sharak", "Durmun", "Ansafir", "Hirzan", "Balzim", 
  "Karfash", "Temlek", "Ebzir", "Ustak", "Bathem", "Izmur", "Kirban", "Sorban", "Bendar", "Jamiron", 
  "Thaldrin", "Muhtesim", "Zahlek", "Ralikar", "Kadim", "Fenur", "Hadran", "Istal", "Sarman", "Tahlem", 
  "Ulanzer", "Bazil", "Abrik", "Urzak", "Lekhem", "Vurhal", "Galbem", "Berash", "Iktar", "Esron", 
  "Jendil", "Zimtar", "Orfash", "Mishrak", "Hafnir", "Kamshal", "Harbith", "Mirzan", "Nuzhal", "Benur", 
  "Sidkar", "Balhon", "Idran", "Labanek", "Karimel", "Zakbel", "Hemazil", "Atram", "Elzefir", "Jubar", 
  "Kazmek", "Beklem", "Athar", "Sabrun", "Hashek", "Omlek", "Hazbel", "Turalis", "Mahtar", "Ulanash", 
  "Zebbar", "Nizan", "Ferzar", "Nusrak", "Iblar", "Haslem", "Talanth", "Jukbel", "Rezmik", "Parzan", 
  "Kurmesh", "Bellar", "Nimrodak", "Uzhel", "Talzir", "Mirkel", "Abranis", "Osfar", "Selinur", "Zaybak", 
  "Malten", "Kirzar", "Ruhel", "Shamelar", "Jasrak", "Thalben", "Zurkan", "Mabrik", "Altharen", "Nemlek", 
  "Oshan", "Idenar", "Zebril", "Hirzan", "Lumeron", "Ebarnis", "Vultar", "Sarunel", "Idiran", "Harzel", 
  "Thasrik", "Herbenar", "Zurbal", "Altimir", "Varsal", "Malikesh", "Barenik", "Darbel", "Reshtan", 
  "Lorbin", "Inzar", "Hamzadir", "Nabtis", "Sebmar", "Tulqar", "Ashzafir", "Mashrik", "Vesdar", "Zoramun", 
  "Krantar",

  "Sierhelt", "Meldrim", "Valtheris", "Israkel", "Tharim", "Zahelt", "Haldrin", "Seldrak", "Jaltrim", "Fendril", 
  "Hesrim", "Tazhelm", "Kaldris", "Zahran", "Ulthir", "Veltrim", "Bralmir", "Selrin", "Zelkor", "Varhim", 
  "Kashel", "Nardrim", "Mirzal", "Ithrel", "Fazrim", "Zeldar", "Azheron", "Beltrim", "Sarnil", "Elgrim", 
  "Malrik", "Festrim", "Dalreth", "Sadril", "Zimreth", "Harhelm", "Nethrim", "Kelrim", "Jathar", "Raldris", 
  "Karhelm", "Nothrim", "Beril", "Valzir", "Zelthir", "Serhil", "Tarmel", "Garmith", "Ulzir", "Vezrim", 
  "Samhelt", "Halith", "Mithral", "Tamelor", "Felrim", "Kardrim", "Zelmir", "Jorhil", "Selrik", "Zelthor", 
  "Tharhil", "Melthar", "Azrim", "Feldrin", "Ulthor", "Tarhek", "Seldrik", "Kelthor", "Vernith", "Jadrim", 
  "Iraldrin", "Barzil", "Serdrin", "Kalthir", "Harzin", "Fedrim", "Selorin", "Tarhel", "Zorhil", "Athrim", 
  "Jarlith", "Thernor", "Velzir", "Zethar", "Karhil", "Seldor", "Irdrel", "Hathrin", "Valhelm", "Kasrim", 
  "Zarhil", "Fenrim", "Tazril", "Harsin", "Vornith", "Seldrim", "Nadril", "Felhin", "Jezrim", "Ralzir", 
  "Balthir", "Zelrim", "Samthor", "Tarhim", "Varhil", "Seltrim", "Farnil", "Haldreth", "Jelthir", "Karnil", 
  "Zorhelm", "Beldrin", "Tarneth", "Ralhim", "Kazrim", "Selgrim", "Barmil", "Varnith", "Jorhelm", "Tharnil", 
  "Harnil", "Kalrim", "Selzor", "Velthar", "Zarhelm", "Barhelm", "Hestrim", "Jalthor", "Veldrin", "Jorhim", 
  "Keltar", "Jorhil", "Harnor", "Selthor", "Tarlim", "Marthir", "Nalthor", "Serhim", "Farhil", "Belhar", 
  "Ralhelm", "Tarzil", "Harnel", "Velthor", "Zeltar", "Maldrim", "Karzin", "Nerhil", "Serthor", "Tormith", 
  "Velzir", "Jorthar", "Kazrel", "Halzin", "Farnor", "Jelzor", "Tharnor", "Velgrim", "Samhelm", "Marhim", 
  "Kazrim", "Balthar", "Jolhim", "Kelzrin", "Falthor", "Varnor", "Zelzor", "Jarneth", "Kelgrim", "Rothar", 
  "Thalgrim", "Harzor", "Selrik", "Felthor", "Ithrin", "Garneth", "Belhelm", "Melhar", "Tharnil", "Veldrim", 
  "Thargrim", "Sarnor", "Varzor", "Jelthar", "Nalthor", "Kazril", "Farneth", "Jarnor", "Tornil", "Kalzrin", 
  
  "Serdrim", "Varnel", "Thalrim", "Zornil", "Karthor", "Tazhel", "Jornil",
  "Bongo", "Skrungus", "Grombo", "Bunkulon", "Dargalo", "Kalimak", "Piom", 
  "Murbag", "Alakryt", "Rugow", "Raczak", "Usztor", "Czilimtar", "Lewizjon", 
  "Kambetar", "Agim", "Tropos", "Drenik", "Torlak", "Doskozil"]
}

export const feminineTharkianNames = {
  type: "picker",
  list: [  "Anzira", "Zilara", "Hathra", "Belit", "Naris", "Selmara", "Mardis", "Orzani", "Shabira", "Zephira", 
  "Althis", "Ilzira", "Hafra", "Nuzira", "Kazira", "Mirzel", "Samrah", "Izdani", "Elnaris", "Bahira", 
  "Asmaris", "Melthia", "Jalith", "Raniah", "Yazira", "Halira", "Zekira", "Arfah", "Lamira", "Izhtir", 
  "Qalith", "Munaqir", "Thalira", "Zantara", "Azenis", "Thamira", "Tamzara", "Nemira", "Ashira", "Samina", 
  "Gelthara", "Narzira", "Elkaris", "Ishtira", "Mazira", "Barizah", "Jandira", "Kahlith", "Olthira", 
  "Zedaria", "Malzira", "Azthira", "Belzira", "Tarnith", "Usira", "Jamira", "Lemna", "Risla", "Namtira", 
  "Kalizah", "Idrania", "Zithara", "Yariza", "Elamira", "Darina", "Mirzim", "Lathira", "Iqra", "Kasira", 
  "Jasmira", "Zafrina", "Ulzira", "Tarina", "Yezla", "Varitha", "Shemara", "Illara", "Bethira", "Hazirah", 
  "Jasira", "Amthira", "Lenira", "Zulnari", "Ferzah", "Kalmina", "Sharith", "Anamara", "Mezira", "Kirith", 
  "Baramith", "Alzira", "Ebthara", "Lemara", "Samthia", "Zehran", "Mirathra", "Ramila", "Khizra", 
  "Jalzira", "Fathara", "Ishnah", "Dirahna", "Ralzira", "Zabira", "Ermina", "Zebaris", "Abina", "Vezrah", 
  "Nathira", "Hizria", "Samarin", "Milzia", "Barinith", "Fethara", "Lazira", "Tarisa", "Yalmira", "Venara", 
  "Lorathra", "Zenithra", "Dazira", "Ulmira", "Salthara", "Jazira", "Zibriah", "Tazina", "Yalmira", 
  "Kamirath", "Benira", "Idirah", "Belnara", "Zofira", "Lizarah", "Arfara", "Selrina", "Mithara", "Varnira", 
  "Amandria", "Jamilith", "Nahlara", "Jasma", "Belzithra", "Lethira", "Selzana", "Ralmira", "Demraza", 
  "Usmina", "Miralia", "Thimira", "Sirithra", "Ormira", "Yalmara", "Ulanira", "Basira", "Zulnazah", 
  "Idhirah", "Abarina", "Lamira", "Zeltira", "Kalzira", "Izimara", "Barzilrah", "Shenira", "Zamira", 
  "Ezirah", "Kamna", "Ferzira", "Valira", "Melkira", "Ismahra", "Zamila", "Tabitha", "Masirah", "Harmira", 
  "Lusmira", "Zelimara", "Yustira", "Azenirah", "Balira", "Temira", "Yalfira", "Zebrina", "Kafira", 
  "Zuzlah", "Samara", "Mirzara", "Zorana", "Thamira", "Selbeth", "Halnira", "Ulzira", "Malfira", "Orimira", 
  "Ramira", "Shadira", "Izlina", "Azkarah", "Abela", "Ferzari", "Nasira",

  "Sierha", "Meldra", "Thalira", "Valthra", "Zarhina", "Selrinia", "Tazira", "Jelra", "Kalina", "Narzira", 
  "Israina", "Heldria", "Fenlira", "Velzira", "Salmira", "Belthira", "Azhera", "Zeldra", "Tarnira", "Karina", 
  "Selina", "Ulthira", "Hathira", "Valzira", "Azrina", "Nethira", "Melthira", "Zarlira", "Belrina", "Serhina", 
  "Kalzira", "Varina", "Nathira", "Zamira", "Heslira", "Felzira", "Vornira", "Ralzira", "Marlira", "Serlira", 
  "Azlira", "Tarmira", "Jarlina", "Selrith", "Kazira", "Harzina", "Nerlira", "Malzira", "Tharnira", "Belnira", 
  "Azlin", "Kelina", "Zelmina", "Tarin", "Serlira", "Kalthira", "Harina", "Jorina", "Feslira", "Ulzira", 
  "Helzira", "Tarzina", "Selina", "Iralira", "Felrina", "Marina", "Thalmira", "Velrina", "Sarnira", "Jorlina", 
  "Tharza", "Belzira", "Varmina", "Kazlira", "Zelmira", "Ralina", "Tarnil", "Jezira", "Selanira", "Zorina", 
  "Ithira", "Thamra", "Kelrina", "Belnira", "Falzira", "Varlira", "Helrin", "Salzira", "Thamira", "Kazelia", 
  "Velrith", "Nethra", "Mirzina", "Sarnila", "Zanira", "Kalzira", "Zarmina", "Ithlira", "Marlina", "Helthira", 
  "Belzara", "Taranil", "Valina", "Seldra", "Kalthira", "Zorin", "Selira", "Narlira", "Belnira", "Tharlira", 
  "Tormira", "Jelra", "Zelmira", "Tharmira", "Farnira", "Kazira", "Selrania", "Jasrina", "Varzina", "Melrina", 
  "Belrith", "Valmin", "Karmina", "Serira", "Harina", "Zorila", "Sarnira", "Thalia", "Zanira", "Felmira", 
  "Narthira", "Mirlina", "Azmira", "Kelira", "Harmira", "Melzira", "Salmira", "Tarnira", "Falzina", "Narnira", 
  "Helzira", "Jathira", "Valina", "Zariza", "Melrina", "Sethira", "Azharina", "Berlina", "Thalina", "Varzina", 
  "Serzina", "Kalthra", "Fesira", "Helmina", "Azlira", "Tharnira", "Varlira", "Ralzina", "Jalrina", "Selrina", 
  "Belina", "Kazina", "Zorira", "Varlina", "Melina", "Harzina", "Tormina", "Thamira", "Velrina", "Azrina", 
  "Selzrina", "Marliza", "Tarlira", "Kazrina", "Zethira", "Narliza", "Thalira", "Sorlira", "Zarnira", "Valzira",

  "Bonga", "Skrunga", "Gromba", "Bunkulona", "Dargala", "Kalimaka", "Pioma", 
  "Murbaga", "Alakryta", "Rugowia", "Raczakia", "Usztora", "Czilimtara", 
  "Lewizjona", "Kambetara", "Agima", "Tropia", "Drenika", "Torlaka", "Doskozila"]
}

export const humanMasculineNames = function (){
  let list = []
  list.push(pickFromList(maleSlavicNames))
  list.push(pickFromList(WHFMaleHumanNames))
  list.push(pickFromList(masculineTharkianNames))
  return {
    type: "pickerRoller",
    list
  }
}

export const humanFeminineNames = function (){
  let list = []
  list.push(pickFromList(feminineTharkianNames))
  return {
    type: "pickerRoller",
    list
  }
}

// export const something = {
//   type: "picker",
//   list: [
//   ],
// };
